# DAQ FOT configuration.

include: config/system/default.yaml

switch_setup:
  of_dpid: 0xfa
  data_intf: alt-intf
  alt_port: 6669
  uplink_port: 100
  ext_br: alt-switch
  model: EXT_STACK

run_trigger:
  vlan_start: 2000
  vlan_end: 2010
  egress_vlan: 171
